description: Comparators for use in this test harness

comparators:
  string_comparator:
    entry_point: string_comparator
    description: Simple string comparison

  python_comparator:
    entry_point: compare_python
    description: Python text comparator

  python_validator:
    entry_point: validate_python
    description: Compare _and_ validate python output

  rdf_comparator:
    entry_point: compare_rdf
    description: compare RDF output. Note optional format parameter.

  jsonld_comparator:
    entry_point: jsonld_comparator

  json_comparator:
    entry_point: jsonld_comparator

  n3_comparator:
    entry_point: n3_comparator

  always_pass_comparator:
    entry_point: always_pass_comparator

  identity_comparator:
    entry_point: always_pass_comparator
