description: Filters for use in this test harness

filters:
  identity_filter:
    entry_point: harness_source.support.filters:identity_filter
    description: Filter w/ no changes
  jupyter_notebook_filter:
    entry_point: harness_source.support.filters:nb_filter
    description: Filter for jupyter (ipynb) notebooks
  yaml_filter:
    entry_point: harness_source.support.filters:yaml_filter
    description: Filter for generated yaml files
  generic_filter:
    entry_point: harness_source.support.filters:metadata_filter
    description: Strip metadata from several types of output
  json_context_filter:
    entry_point: harness_source.support.filters:json_metadata_context_filter
    description: Filter for some json contexts
  json_filter:
    entry_point: harness_source.support.filters:json_metadata_filter
    description: filter for json output
  ldcontext_filter:
    entry_point: harness_source.support.filters:ldcontext_metadata_filter
    description: filter for json-ld context
