description: Filters for use in this test harness

filters:
  identity_filter:
    entry_point: identity_filter
    description: Same as no filter
  jupyter_notebook_filter:
    entry_point: nb_filter
    description: Filter for jupyter (ipynb) notebooks
  yaml_filter:
    entry_point: yaml_filter
    description: Filter for generated yaml files
  generic_metadata_filter:
    entry_point: metadata_filter
    description: Strip metadata from several types of output
  json_metadata_context_filter:
    entry_point: json_metadata_context_filter
    description: Filter for some json contexts
  json_metadata_filter:
    entry_point: json_metadata_filter
    description: filter for json output
  ldcontext_metadata_filter:
    entry_point: ldcontext_metadata_filter
    description: filter for json-ld context
