tests:
  owlgen:
    tests:
      - target:
          path: linkml_source/meta.owl
        source:
          path: linkml_source/meta.yaml
        use_stdout: True

  jsonldcontextgen:
    tests:
      - target:
          path: linkml_source/types.context.jsonld
        source:
          path: linkml_source/types.yaml
        use_stdout: True
      - target:
          path: linkml_source/mappings.context.jsonld
        source:
          path: linkml_source/mappings.yaml
        use_stdout: True
      - target:
          path: linkml_source/extensions.context.jsonld
        source:
          path: linkml_source/extensions.yaml
        use_stdout: True
      - target:
          path: linkml_source/annotations.context.jsonld
        source:
          path: linkml_source/annotations.yaml
        use_stdout: True
      - target:
          path: linkml_source/units.context.jsonld
        source:
          path: linkml_source/units.yaml
        use_stdout: True
      - target:
          path: linkml_source/validation.context.jsonld
        source:
          path: linkml_source/validation.yaml
        use_stdout: True

  jsongen:
    tests:
      - target:
          path: linkml_source/types.json
        source:
          path: linkml_source/types.yaml
        use_stdout: True
      - target:
          path: linkml_source/mappings.json
        source:
          path: linkml_source/mappings.yaml
        use_stdout: True
      - target:
          path: linkml_source/extensions.json
        source:
          path: linkml_source/extensions.yaml
        use_stdout: True
      - target:
          path: linkml_source/annotations.json
        source:
          path: linkml_source/annotations.yaml
        use_stdout: True
      - target:
          path: linkml_source/units.json
        source:
          path: linkml_source/units.yaml
        use_stdout: True
      - target:
          path: linkml_source/validation.json
        source:
          path: linkml_source/validation.yaml
        use_stdout: True

  prefixmapgen:
    tests:
      - target:
          path: prefixtest.context.jsonld
        source:
          path: prefixtest.yaml
        parameters: -o {outfile}

      - target:
          path: help
        parameters: --help
        use_stdout: True

