description: modules to be tested
modules:
  csv_dumper:
    entry_point: ep
    comparator: c
    subsets: dumper_tests

  json_dumper:
    entry_point: ep
    comparator: c
    subsets: dumper_tests

  rdf_dumper:
    entry_point: ep
    comparator: c
    subsets: dumper_tests

  rdflib_dumper:
    entry_point: ep
    comparator: c
    subsets: dumper_tests

  yaml_dumper:
    entry_point: ep
    comparator: c
    subsets: dumper_tests

  csv_loader:
    entry_point: ep
    comparator: c
    subsets: loader_tests

  json_loader:
    entry_point: ep
    comparator: c
    subsets: loader_tests

  rdf_loader:
    entry_point: ep
    comparator: c
    subsets: loader_tests

  rdflib_loader:
    entry_point: ep
    comparator: c
    subsets: loader_tests

  yaml_loader:
    entry_point: ep
    comparator: c
    subsets: loader_tests

  csvgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  docgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  dotgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  excelgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  golrgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  graphqlgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  javagen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  jsonldcontextgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  jsonldgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  jsonschemagen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  linkmlgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  markdowngen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  namespacegen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  oocodegen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  owlgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  prefixmapgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  projectgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  protogen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  pydanticgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  pythongen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  rdfgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  shaclgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  shexgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  sparqlgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  sqlalchemygen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  sqlddlgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  sqltablegen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  sssomgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  summarygen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  terminusdbgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  typescriptgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  yamlgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests

  yumlgen:
    entry_point: ep
    comparator: c
    subsets: generator_tests


